### PR TITLE
Enhance type detection for internal php functions `key`, `current`, `end` and `reset`

### LINKED ISSUE #8521: Incorrect type inference when using `key`/`current`/`reset` on non-empty array
Hey there,

when both key and value types of an array are known, I'd expect psalm to be able to infer the return value of `key`/`current` in case of a `non-empty-array` or `non-empty-list`.

https://psalm.dev/r/bc365e8080

Not sure if this can already be done with some conditional magic (even tho, I did never understood how these internal functions are typed 😅).

But something like this might work, right?
```php
/**
  * @template T of array-key
  * @param array<T,mixed> $array
  * @return ($array is non-empty-list ? 0|positive-int : ($array is non-empty-array ? T : mixed))
  */
function key(array $array): mixed
{
}

/**
  * @template T
  * @param array<mixed,T> $array
  * @return ($array is non-empty-list ? T : ($array is non-empty-array ? T : T|false))
  */
function current(array $array): mixed
{}

/**
  * @template T
  * @param array<mixed,T> $array
  * @return ($array is non-empty-list ? T : ($array is non-empty-array ? T : T|false))
  */
function reset(array $array): mixed
{}
```

### PR DESCRIPTION
**Pull request by boesing**
Fixes #8521

### CODE REVIEW

File: tests/ArrayFunctionCallTest.php [hunk 1]
```diff
@@ -9,7 +9,7 @@
 
 class ArrayFunctionCallTest extends TestCase
 {
-    use InvalidCodeAnalysisTestTrait;
+//    use InvalidCodeAnalysisTestTrait;
```
Comment (orklah) [inline tests/ArrayFunctionCallTest.php:12]: this should be restored :)

File: stubs/CoreGenericFunctions.phpstub [hunk 2]
```diff
@@ -136,14 +136,54 @@ function array_flip(array $array)
  *
  * @param TArray $array
  *
- * @return (TArray is array<empty, empty> ? null : TKey|null)
+ * @return (TArray is array<empty,empty> ? null : (TArray is non-empty-list ? int<0,max> : (TArray is non-empty-array ? TKey : mixed)))
```
Comment (orklah) [inline stubs/CoreGenericFunctions.phpstub:139]: Mixed should be replaced by TKey|null

You excluded the empty array and the non-empty-array but it doesn't mean there's nothing left. You still have the simple array type where you don't know if there is content in the array. And in this case you still can't say if it will return null or TKey

**Comment by boesing** [comment]
Fixed all issues.

**Comment by orklah** [comment]
Seems good!
