### PR TITLE
Fix mb_convert_encoding to accept any array.

### LINKED ISSUE #6886: Various problems with mb_convert_encoding
https://psalm.dev/r/fb4e03dccd

# :heavy_check_mark: Case 1 – ``string`` input

> INFO: Trace - $case1: false|string

Return type ``false|string`` – everthing as expected, ok.

# :x: Case 2 – ``array<int, string>`` input

> INFO: Trace - $case2: array<int, string>

Return type ``array<int, string>`` – don’t know how to force some error to test and didn’t found out by looking at the PHP source code, but I suspect it also returns ``false`` in case of an error so the correct return type would probably be ``false|array<int, string>`` in that case.

# :x: Case 3 – ``array<string, string>`` input

> ERROR: InvalidCast - array{idx: "abc"} cannot be cast to string
> ERROR: InvalidArgument - Argument 1 of mb_convert_encoding expects string, array{idx: "abc"} provided
> INFO: Trace - 21:2 - $case3: false|string

Psalm seems to expect ``string|array<int, string>`` as type for the first function parameter. A short test shows the functions also works with ``array<string, string>`` as input:

```php
var_dump(mb_convert_encoding(['idx1' => 'abc', 'idx2' => 'abc'], 'ASCII'));
var_dump(mb_convert_encoding([123 => 'abc', 456 => 'abc'], 'ASCII'));
```
results in
```
array(2) {'idx1' => string(3) "abc", 'idx2' => string(3) "abc"}
array(2) {[123] => string(3) "abc", [456] => string(3) "abc"}
```
so array indexes won’t be touched by php.

# :x: Case 4 – ``string|array`` input

> INFO: MixedArgumentTypeCoercion - Argument 1 of mb_convert_encoding expects array<int, string>, parent type array<array-key, mixed>|string provided
> INFO: Trace - $case4: array<int, string>

Return type should be something like ``array<array-key, mixed>|string|false`` instead.

### PR DESCRIPTION
**Pull request by rarila**
Fixes #6886

### CODE REVIEW

**Comment by orklah** [comment]
Thanks! Do you know if the shape of the array is preserved?

If it is, we could create a stub in order to make the array shape pass through the function.

something like 
```
/**
 * @template T of array|string
 * @param T $string
 * @return (T is array ? T : string)
 */
```
should do the trick

**Comment by rarila** [comment]
Running tests locally at the moment…
.............................................................  610 / 6499 (  9%)
two hours later… :-))

Hmm, no, it isn’t. Look at the last example in the issue. String keys are translated, objects/recursively referenced values are replaced.

So I guess, no

**Comment by weirdan** [comment]
>  two hours later… :-))

Tests shouldn't be that slow, even with Xdebug enabled (I'd suggest to disable it with, e.g. https://packagist.org/packages/weirdan/run-without-xdebug though).

**Comment by orklah** [comment]
> String keys are translated, objects/recursively referenced values are replaced.

Yeah, string are transformed, but the general shape of the array is kept, no? I mean, if the array was `array<int, string>` it will stay a `array<int, string>` right?

**Comment by weirdan** [comment]
> I mean, if the array was array<int, string> it will stay a array<int, string> right?

Yeah, but `array{€:string}` does not stay that way: https://3v4l.org/djRjL, and you wouldn't be able to express that with templates.

**Comment by rarila** [comment]
@weirdan Yep.

**Comment by weirdan** [comment]
> Tests shouldn't be that slow

It takes about 5 minutes here, using `php-noxdebug vendor/bin/paratest` command.

**Comment by rarila** [comment]
@weirdan gonna try, but I’m already at 44% now – almost done :-)

**Comment by orklah** [comment]
Oh yeah, forgot about literals in array-shapes.

Guess it would need a return type provider in order to recursively strip any string literal.

It may be worth it one day, returning `array` is a sure way to trigger a lot of MixedAssignment just by using the returned array

**Comment by rarila** [comment]
Probably 

/**
 * @template T of array|string
 * @param T $string
 * @return (T is array<int, string> ? array<int, string> : 
 *                T is array                    ? array : 
 *                                                    string)
 */

Would help for most cases

**Comment by orklah** [comment]
Yeah, it would, Mind adding that to the stubs?

**Comment by rarila** [comment]
@orklah ok

**Comment by orklah** [comment]
Note that you have to make a change to CallMap_80 and possibly CallMap_historical for your PR to pass the CI. More is explained here: https://psalm.dev/docs/contributing/editing_callmaps/

**Comment by rarila** [comment]
@orklah CoreGenericFunctions.phpstub? Just add it at the end?

**Comment by rarila** [comment]
@orklah 

How do you like this format:

```
/**
 * @template T of array|string
 * @param T $string
 * @return (T is array<int, string> ? array<int, string> : 
 *          T is array              ? array : 
 *          T is string             ? string :
 *                                    never)
 */
```
I like it that way because it lists all possible options and is quite readable that way.

**Comment by orklah** [comment]
Please don't add never at the end. Listing the allowed params is enough to make Psalm emit an issue. Adding never will just create a whole new set of weird errors that will be irrelevant

**Comment by rarila** [comment]
@orklah ok.

Looking at the other callmaps now…

If I see it right, I'll have to remove the array version from CallMap_historical.php, add it to 'added' CallMap_72_delta.php?!

**Comment by orklah** [comment]
nah, you have to change the signature in CallMap_80 "new" to match with the one in your CallMap file and then, if needed, change the CallMap_historical to match with the CallMap_80 "old" (we start from CallMap and then process each delta file from newer to older untli CallMap_historical)

**Comment by rarila** [comment]
I think I have it, running tests…

File: dictionaries/CallMap_72_delta.php [hunk 1]
```diff
@@ -34,6 +34,7 @@
     'ldap_exop_whoami' => ['string|false', 'ldap'=>'resource'],
     'ldap_parse_exop' => ['bool', 'ldap'=>'resource', 'result'=>'resource', '&w_response_data='=>'string', '&w_response_oid='=>'string'],
     'mb_chr' => ['string|false', 'codepoint'=>'int', 'encoding='=>'string'],
+    'mb_convert_encoding\'1' => ['array', 'string'=>'array', 'to_encoding'=>'string', 'from_encoding='=>'mixed'],
```
Comment (orklah) [inline dictionaries/CallMap_72_delta.php:37]: Oh, nice catch! I didn't know arrays were introduced in 7.2

Comment (rarila) [reply dictionaries/CallMap_72_delta.php:37]: At least the manual says so :-)

File: stubs/CoreGenericFunctions.phpstub [hunk 2]
```diff
@@ -1300,4 +1300,11 @@ function get_defined_constants(bool $categorize = false): array {}
...
  * @return ($allow_string is false ? ($object_or_class is object ? bool : false) : bool)
  */
-function is_a($object_or_class, string $class, $allow_string = false): bool{}
\ No newline at end of file
+function is_a($object_or_class, string $class, $allow_string = false): bool{}
+
+/**
+ * @template T of array|string
+ * @param T $string
+ * @return (T is array<int, string> ? array<int, string> : T is array ? array : string)
```
Comment (orklah) [inline stubs/CoreGenericFunctions.phpstub:1308]: we should add |false everywhere in the return types

Comment (rarila) [reply stubs/CoreGenericFunctions.phpstub:1308]: Ah, good catch. But only at the string return.

I still wonder what happens, when you add a string that triggers returning false for a string into an array…

**Comment by orklah** [comment]
Can you add a `@psalm-ignore-falsable-return` on the stub? It will allow people with the config disabled to not handle the false return without getting errors

**Comment by rarila** [comment]
@orklah Here you are :-)

**Comment by orklah** [comment]
Thank you! That's great!

**Comment by rarila** [comment]
No, I have to thank for this great tool!
