### PR TITLE
Fix false positive for unused variable in try (fixes #7613).

### LINKED ISSUE #7613: False-positive for "unused" variable in try-catch
https://psalm.dev/r/585b7b7e67

### PR DESCRIPTION
**Pull request by AndrolGenhald**
I was originally targeting master out of habit, but I figure this is a simple enough bugfix that can go on 4.x, so I cherry picked it over there instead. Note for master: in AssignmentAnalyzer.php `$array_var_id` needs changed to `$extended_var_id`. The only other conflicts should be added tests.

### CODE REVIEW

File: tests/TaintTest.php [hunk 1]
```diff
@@ -2285,6 +2285,25 @@ function sinkNotWorking($sink) : string {}
...
+
+                    try {
+                        $tainted = escapeHtml($tainted);
+                    } catch (Throwable $_) {
+                    }
+
+                    echo $tainted;
+                ',
+                'error_message' => 'TaintedHtml',
+            ],
```
Comment (AndrolGenhald) [inline tests/TaintTest.php:2306]: This test actually passes already, but I left it here anyway in case `try/catch/finally` analysis improves in the future and accidentally breaks it.

File: src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php [hunk 2]
```diff
@@ -86,9 +86,11 @@ public static function analyze(
 
         $old_referenced_var_ids = $try_context->referenced_var_ids;
 
+        $context->inside_try = true;
```
[the remark this answers is not in the document]
Comment (AndrolGenhald) [reply src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php:89]: Good catch! I added a test and fixed it.

[the remark this answers is not in the document]
Comment (orklah) [reply src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php:89]: I fixed a few of those already, they're hard to debug once they're in the codebase, My eye twitch a little whenever I see one now 😄

File: tests/UnusedVariableTest.php [hunk 3]
```diff
@@ -3416,6 +3453,49 @@ function takesArray($a) : void {
...
+                            $step = 3;
+                            $step = 4;
+                        } finally {
+                            echo $step;
+                        }
+                    } finally {
+                    }
+                ',
+                'error_message' => 'UnusedVariable',
+            ],
```
Comment (AndrolGenhald) [inline tests/UnusedVariableTest.php:3498]: I think fixing this will be a lot more difficult, but it's probably not too common anyway, so I'll just leave it for now.

File: src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php [hunk 4]
```diff
@@ -86,11 +86,12 @@ public static function analyze(
 
         $old_referenced_var_ids = $try_context->referenced_var_ids;
 
+        $previously_inside_try = $context->inside_try;
```
Comment (orklah) [inline src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php:89]: Sorry, I'll nitpick, can you name it `was_inside_try` for consistency?

Comment (orklah) [reply src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php:89]: This is the convention that has been used for every context flag like this

File: tests/UnusedVariableTest.php (hunk 3 above)
Comment (orklah) [reply tests/UnusedVariableTest.php:3498]: no worries :)

File: src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php (hunk 4 above)
Comment (AndrolGenhald) [reply src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php:89]: Didn't notice we already had a convention there.

**Comment by orklah** [comment]
Thanks!
