### PR TITLE
fix: pass along final

### LINKED ISSUE #3470: [False Positive] Unnecessary &static required in typehint
I believe this was just a regression introduced in 3.11.5, as one of my tests over @ the laravel plugin just started failing.

https://psalm.dev/r/64c4862e7e

I don't believe the additional `&static` is necessary, since `User` is `final`.

Marking the template as covariant is a workaround

### PR DESCRIPTION
**Pull request by mr-feek**
closes #3470 

I can make a separate test case if you like. I figured it was fine to merge them together since the title of the test case was `inheritTemplatedMixinWithStatic`

### CODE REVIEW

File: tests/MixinAnnotationTest.php [hunk 1]
```diff
@@ -243,10 +243,10 @@ public function __construct ($var) {
                         }
 
                         /**
-                         * @psalm-return T
+                         * @psalm-return self<T>
```
Comment (muglug) [inline tests/MixinAnnotationTest.php:246]: Any reason why you can't just create a new test?

Comment (mr-feek) [reply tests/MixinAnnotationTest.php:246]: figured it'd be a lot of boilerplate, happy to do so :) I'll push it up in a sec

**Comment by muglug** [comment]
Thanks!
