### PR TITLE
Fix #8735: IntlDateFormatter CallMaps.

### LINKED ISSUE #8735: IntlDateFormatter::__construct (and probably other methods) CallMap is incorrect
Regarding https://psalm.dev/r/b6ebba0bf1 and [the PHP Documentation](https://www.php.net/manual/en/class.intldateformatter.php), it looks like the CallMap is KO about this.

Looking at the current CallMap I found, it looks like also IntlDateFormatter::create(…) is not OK, so maybe a global review of the CallMap for this class could be done.

I wish I could update it but looking as PhpStorm's stubs, this method changed a lot from PHP 5.3 to PHP 8.1 and I'm not sure how can I update the CallMap files accordingly, neither how can I test it.
If someone can provide just a single example of how to update the CallMap (+ maybe specific CallMaps for PHP 8.0, PHP 8.1…) correctly of one single method, then I could spend some time to replicate this to the whole class myself.

Thanks a lot.

### PR DESCRIPTION
**Pull request by niconoe-**

### CODE REVIEW

File: dictionaries/CallMap_historical.php [hunk 1]
```diff
@@ -3340,28 +3340,27 @@
...
+    'IntlDateFormatter::create' => ['?IntlDateFormatter', 'locale'=>'?string', 'datetype'=>'null|int', 'timetype'=>'null|int', 'timezone='=>'IntlTimeZone|DateTimeZone|string|null', 'calendar='=>'IntlCalendar|int|null', 'pattern='=>'?string'],
+    'IntlDateFormatter::format' => ['string|false', 'value'=>'IntlCalendar|DateTime|array{0: int, 1: int, 2: int, 3: int, 4: int, 5: int, 6: int, 7: int, 8: int}|array{tm_sec: int, tm_min: int, tm_hour: int, tm_mday: int, tm_mon: int, tm_year: int, tm_wday: int, tm_yday: int, tm_isdst: int}|string|int|float'],
+    'IntlDateFormatter::formatObject' => ['string|false', 'object'=>'IntlCalendar|DateTime', 'format='=>'array{0: int, 1: int}|int|string|null', 'locale='=>'?string'],
     'IntlDateFormatter::getCalendar' => ['int'],
     'IntlDateFormatter::getCalendarObject' => ['IntlCalendar'],
     'IntlDateFormatter::getDateType' => ['int'],
     'IntlDateFormatter::getErrorCode' => ['int'],
     'IntlDateFormatter::getErrorMessage' => ['string'],
-    'IntlDateFormatter::getLocale' => ['string|false'],
+    'IntlDateFormatter::getLocale' => ['string', 'which='=>'int'],
```
Comment (orklah) [inline dictionaries/CallMap_historical.php:3352]: The doc doesn't have a `which` param: https://www.php.net/manual/fr/intldateformatter.getlocale.php

Is this a doc error?

Comment (orklah) [reply dictionaries/CallMap_historical.php:3352]: nvm, you changed the name on more recent versions :)

Comment (niconoe-) [reply dictionaries/CallMap_historical.php:3352]: Yes, the parameter changed approximatively when PHP 8.0 rolled out.

See a former documentation of the exact same page from May 2020 for instance: https://web.archive.org/web/20200502000358/https://www.php.net/manual/fr/intldateformatter.getlocale.php
