### PR TITLE
Fix excluding binary path under Windows

### LINKED ISSUE #5621: No issues locally but issues in GitHub actions and other environments
https://github.com/yiisoft/factory/pull/78/files - there are issues but locally I don't get any.

To reproduce:

1. `clone https://github.com/yiisoft/factory.git`
2. `git checkout -b new-config origin/new-config`
3. `composer update`
4. `./vendor/bin/psalm --no-cache`

```
Scanning files...
Analyzing files...

░

To whom it may concern: Psalm cannot detect unused classes, methods and properties
when analyzing individual files and folders. Run on the full project to enable
complete unused code detection.
------------------------------
No errors found!
------------------------------

Checks took 1.33 seconds and used 225.092MB of memory
Psalm was unable to infer types in the codebase
```

Weird thing is that colleagues are getting the errors doing the same actions. Additional info:

1. Psalm 4.7.0@d4377c0baf3ffbf0b1ec6998e8d1be2a40971005
2. PHP 8.0.3, also tried with PHP 7.4.11.
3. Windows 10 with git bash set as shell.

### PR DESCRIPTION
**Pull request by samdark**
Fixes #5621.

### CODE REVIEW

File: src/command_functions.php [hunk 1]
```diff
@@ -229,7 +229,10 @@ function getPathsToCheck($f_paths): ?array
             /** @var string */
             $input_path = $input_paths[$i];
 
-            if (realpath($input_path) === realpath(dirname(__DIR__) . DIRECTORY_SEPARATOR . 'psalm')
+            if (
+                realpath($input_path) === realpath(dirname(__DIR__, 3) . DIRECTORY_SEPARATOR . 'bin' . DIRECTORY_SEPARATOR . 'psalm')
```
Comment (weirdan) [inline src/command_functions.php:233]: Does this mean `vendor/bin/psalm` is not a symlink (or whatever equivalent Windows has for symlinks) on Windows?

Comment (samdark) [reply src/command_functions.php:233]: Yes. On Windows Composer, instead of using symlinks, is creating batch-files, such as `psalm.bat` with the following content:

Comment (samdark) [reply src/command_functions.php:233]: And bash-specific files are alike with content and adjusted paths. Not symlinks.

Comment (weirdan) [reply src/command_functions.php:233]: For future references: when installation is run on Windows or when [`bin-compat`](https://getcomposer.org/doc/06-config.md#bin-compat) flag is set to `full` Composer generates files like this: https://github.com/composer/composer/blob/c3b76a85329c60220588e861eee02c2d0150c5ce/src/Composer/Installer/BinaryInstaller.php#L187

**Comment by weirdan** [comment]
Mind fixing CodeSniffer nitpicks?

**Review by weirdan — APPROVED** [review]

**Comment by samdark** [comment]
Fixed.

**Comment by muglug** [comment]
Thanks!

**Comment by samdark** [comment]
Do you plan tagging a release? I'd love to have this fixed in my projects.

// And thank you and the whole team very much for an awesome tool!
