### PR TITLE
Fix generic object comparison to use template constraint as default.

### LINKED ISSUE #8068: class-string false positive for constrained template
https://psalm.dev/r/b2a12349ff

Since `Foo`'s template is constrained to `string` and `bar` takes `class-string<Foo>`, it should default that template to `class-string<Foo<string>>` and `Foo::class` should satisfy that.

Related to #7913 (which is for the case where `bar` takes something like `class-string<Foo<non-empty-string>>` which is currently impossible to satisfy), but this is a special case that should be easy to fix.

### PR DESCRIPTION
**Pull request by AndrolGenhald**
Fixes #8068.

### CODE REVIEW

**Comment by AndrolGenhald** [comment]
This will conflict with #8044 when both are merged to master, this one is correct.

File: src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php [hunk 1]
```diff
@@ -1134,7 +1136,21 @@ public static function getMappedGenericTypeParams(
...
+
+            $container_class = $container_type_part->value;
+
+            if (strtolower($input_type_part->value) === strtolower($container_type_part->value)) {
+                $input_type_params = $class_storage->getClassTemplateTypes();
+            } elseif (!empty($class_storage->template_extended_params[$container_class])) {
+                $input_type_params = array_values($class_storage->template_extended_params[$container_class]);
+            } else {
+                $input_type_params = array_fill(0, count($class_storage->template_types ?? []), Type::getMixed());
+            }
```
Comment (AndrolGenhald) [inline src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php:1152]: This will conflict with https://github.com/vimeo/psalm/pull/8044 when both are merged to master, this one is correct.

**Comment by orklah** [comment]
Thanks!
