### PR TITLE
Nicer PHP version checking

### LINKED ISSUE #10084: UnexpectedValueException: Expecting a version number in the format x.y
### Steps to reproduce
1. Set [`phpVersion`](https://psalm.dev/docs/running_psalm/configuration/#phpversion) to `"5.1"` in the configuration file.
2. Run Psalm.

#### Actual result
~~~
Uncaught UnexpectedValueException: Expecting a version number in the format x.y in /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php:1174
Stack trace:
#0 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/CliUtils.php(500): Psalm\Internal\Analyzer\ProjectAnalyzer->setPhpVersion('5.1', 'config')
#1 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(349): Psalm\Internal\CliUtils::initPhpVersion(Array, Object(Psalm\Config), Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#2 /opt/psalm/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#3 /opt/psalm/vendor/bin/psalm(119): include('/opt/psalm/vend...')
#4 {main}
(Psalm 5.11.0@c9b192ab8400fdaf04b2b13d110575adc879aa90 crashed due to an uncaught Throwable)
~~~

#### Expected result
1. No uncaught exception, no stack trace.
2. Correct error message telling that PHP 5.1 specified in the configuration file "<filepath>.xml" is not supported by Psalm, and only PHP 5.4-5.6, 7.0-7.4, 8.0-8.2 are supported.

### Root cause
https://github.com/vimeo/psalm/blob/dc8163011d4afb3b8eb638a4990b1c8e62a08f2f/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php#L1182-L1184

### Additional information
The error message is also wrong because actually version numbers in the formats x.y.z (e.g. "8.2.8") are also expected.

### PR DESCRIPTION
**Pull request by Nitamet**
Resolves #10084 

There are now separate checks for version format and supported versions
If the version is invalid or unsupported, CLI now doesn't throw an error and print the stacktrace, just prints the error message and exits

### CODE REVIEW

File: src/Psalm/Internal/Analyzer/ProjectAnalyzer.php [hunk 1]
```diff
@@ -200,6 +200,10 @@ class ProjectAnalyzer
         UnnecessaryVarAnnotation::class,
     ];
 
+    private const PHP_VERSION_REGEX = '^(0|[1-9]\d*)\.(0|[1-9]\d*)(?:\..*)?$';
+
+    private const PHP_SUPPORTED_VERSIONS_REGEX = '^(5\.[456]|7\.[01234]|8\.[012])(\..*)?$';
```
Comment (weirdan) [inline src/Psalm/Internal/Analyzer/ProjectAnalyzer.php:205]: 8.3 is partially supported now, so it would make sense to allow it here as well

File: src/Psalm/Internal/Analyzer/ProjectAnalyzer.php [hunk 2]
```diff
@@ -1179,10 +1183,27 @@ public function refactorCodeAfterCompletion(array $to_refactor): void
...
+        if (!preg_match('/' . self::PHP_SUPPORTED_VERSIONS_REGEX . '/', $version)) {
+            fwrite(
+                STDERR,
+                'Psalm supports PHP version ">=5.4". The specified version '
+                . $version
+                . " is either not supported or doesn't exist."
+                . PHP_EOL,
+            );
+            exit(1);
+        }
```
Comment (weirdan) [inline src/Psalm/Internal/Analyzer/ProjectAnalyzer.php:1204]: `exit(1)` is reserved for when Psalm finds some issues with the codebase it inspects, see https://psalm.dev/docs/running_psalm/command_line_usage/#exit-status
 
Also, this method is used in a lot of tests, and exception is so much more useful in tests compared to outright crash. Please keep the exception, but catch it in `CliUtils::initPhpVersion()` and `exit(2)` there instead.

**Review by weirdan — CHANGES_REQUESTED** [review]

**Comment by Nitamet** [comment]
Changed the code according to the comments.

**Review by weirdan — APPROVED** [review]

**Comment by weirdan** [comment]
Thanks!

File: src/Psalm/Internal/Analyzer/ProjectAnalyzer.php (hunk 2 above)
Comment (weirdan) [reply src/Psalm/Internal/Analyzer/ProjectAnalyzer.php]: Actually it's the other way around. `exit(1)` is for general problems, and `exit(2)` is for successful run that found some code issues.

Comment (weirdan) [reply src/Psalm/Internal/Analyzer/ProjectAnalyzer.php]: Sorry for the confusion. I'll fix it myself.
