### PR TITLE
Fix race condition creating parser cache directory (fixes #4483)

### LINKED ISSUE #4483: PHP Warning
Occasionally psalm gives me this PHP warning:

```
PHP Warning:  mkdir(): File exists in /app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ParserCacheProvider.php on line 244
```

### PR DESCRIPTION
**Pull request by AndrolGenhald**
I wasn't able to reproduce the error under normal conditions, but I set a breakpoint on the `mkdir` call, created the directory, then continued, and it seems to handle it correctly.

### CODE REVIEW

File: src/Psalm/Internal/Provider/ParserCacheProvider.php [hunk 1]
```diff
@@ -402,4 +400,18 @@ private function getParserCacheKey(string $file_name): string
     {
         return md5($file_name) . ($this->use_igbinary ? '-igbinary' : '') . '-r';
     }
+
+    private function createCacheDirectory(string $parser_cache_directory): void
+    {
+        if (!is_dir($parser_cache_directory)) {
```
Comment (weirdan) [inline src/Psalm/Internal/Provider/ParserCacheProvider.php:406]: wouldn't `@mkdir(...)` make more sense? After all, we only want the directory to exist. On the other hand this could just move race-condition elsewhere.

Comment (AndrolGenhald) [reply src/Psalm/Internal/Provider/ParserCacheProvider.php:406]: _Technically_ it could be a file for some reason, in which case an error should be thrown, but I wouldn't really be opposed to changing it to `@mkdir(...)`, as it being a file seems incredibly unlikely.

I suppose you're right that this could just move the race condition somewhere else, I hadn't considered that. I haven't really looked into how the caching works, hopefully different processes aren't going to be using the same `$file_cache_key`.

Comment (AndrolGenhald) [reply src/Psalm/Internal/Provider/ParserCacheProvider.php:406]: `mkdir` could also fail due to lack of write permission, which also seems unlikely, but more likely than the directory path being a file.

**Comment by muglug** [comment]
Thanks!
