### PR TITLE
Fix ambiguous constant inheritance false positive

### LINKED ISSUE #7818: AmbiguousConstantInheritance does not handle multiple interhitances of same interface
https://psalm.dev/r/b1dfb3d8c0

We are using a similar construct. A main interface for all Services, and several interfaces for what the Service supports. The supporting interface must implement ServiceInterface, so we are clear that it is a service interface.

ServiceWithPermissionsInterface extends ServiceInterface
DistributeableServiceInterface extends ServiceInterface

etc.

Tried to add `final` to solve the problem, but it just became worse. PHP itself handles the `final` very well.
https://psalm.dev/r/99f7bf3fc4

### PR DESCRIPTION
**Pull request by Jean85**
Fixes #7818

Thanks to @orklah for [his comment](https://github.com/vimeo/psalm/issues/7818#issuecomment-1371420642), that allowed me to fix this even without knowing anything about the Psalm codebase!

I've used https://psalm.dev/r/99f7bf3fc4 as a regression test.

### CODE REVIEW

**Comment by Jean85** [comment]
Ouch, the failing test is highlighting that my fix is too shallow, it swallows the error from the docs snippet. Any pointers?

**Comment by orklah** [comment]
Thanks for this!

There's 3 variables with a constant in that code

$const_storage: it's received as a param. It's the storage of the constant retrieved from the class storage of Baz (it's arbitrarily chosen from the 2 constant storage that exists for Baz::CONSTANT)
$parent_const_storage: it's the constant storage that is retrieved from the interface that we're looking for in the current iteration of the loop
$interface_const_storage: it's the constant storage that was retrieved from the interface we were looking on the previous iteration of the loop

So when everything is ok, we iterate for each interface, we check for the existence of that constant. If it doesn't exists, we continue looping until we found that constant in one interface. When that happens we store the storage for comparison with the next iteration:
https://github.com/vimeo/psalm/blob/8c491e93e8a4bc0934f07fa232ae4bd8124b58aa/src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php#L859 

So your code compares the arbitrary constant storage with the current constant storage so the result is arbitrary. What you want to do is compare the storage between two interfaces, so between two iterations of the loop (so between  $parent_const_storage and $interface_const_storage)

As a note: you should be able to directly compare storages instead of comparing the hash of their location given each instance is should be unique

File: src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php [hunk 1]
```diff
@@ -844,6 +844,7 @@ private static function getOverriddenConstant(
                     assert($parent_classlike_storage !== null);
                     if (!isset($parent_classlike_storage->parent_interfaces[strtolower($interface)])
                         && !isset($interface_storage->parent_interfaces[strtolower($parent_classlike_storage->name)])
+                        && $interface_const_storage->stmt_location !== $parent_const_storage->stmt_location
```
Comment (orklah) [inline src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php:847]: $interface_const_storage !== $parent_const_storage should be good too :)

Comment (Jean85) [reply src/Psalm/Internal/Analyzer/Statements/Expression/ClassConstAnalyzer.php]: Done in e8bc9a620

**Comment by orklah** [comment]
Thanks!
