### PR TITLE
type of "$http_response_header" is "list<string>" now

### LINKED ISSUE #6456: Incorrect type for reserved $http_response_header variable: array<array-key, mixed> instead of list<string>
https://psalm.dev/r/ca2f17ab48

According to the PHP documentation, $http_response_header is a list of strings.
https://www.php.net/manual/en/reserved.variables.httpresponseheader.php

### PR DESCRIPTION
**Pull request by SMAtaurRahman**
Fixes #6456 

Let me know if this one requires test cases. I couldn't figure out how/where to write tests.

### CODE REVIEW

File: src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php [hunk 1]
```diff
@@ -38,7 +38,6 @@ class VariableFetchAnalyzer
         '$_SESSION',
         '$_REQUEST',
         '$_ENV',
-        '$http_response_header',
```
Comment (weirdan) [inline src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php:41]: This is used in other places as well (via `VariableFetchAnalyzer::isSuperGlobal()`) so it's safer to keep it on this list and just override the type, like you did below.

**Review by weirdan — CHANGES_REQUESTED** [review]

**Review by weirdan — APPROVED** [review]

**Comment by weirdan** [comment]
Thanks!
