### PR TITLE
Initial inferred Closure Returns

### LINKED ISSUE #2896: Infer closure param types from return type closure params
These three should not have any errors:

```php
/**
 * @template T
 * @template U
 * @param callable(T): U $predicate
 * @return Closure(iterable<T>): iterable<U>
 */
function map(callable $predicate): callable {
    return function($iter) use ($predicate): iterable {
        foreach ($iter as $key => $value) {
            yield $key => $predicate($value);
        }
    };
}
```

```php
/**
 * @template T
 * @template U
 * @param callable(T): U $predicate
 * @return Closure(iterable<T>): iterable<U>
 */
function map(callable $predicate): callable {
    return function(iterable $iter) use ($predicate): iterable {
        foreach ($iter as $key => $value) {
            yield $key => $predicate($value);
        }
    };
}
```

```php
/**
 * @template T
 * @template U
 * @param callable(T): U $predicate
 * @return callable(iterable<T>): iterable<U>
 */
function map(callable $predicate): callable {
    return function($iter) use ($predicate): iterable {
        foreach ($iter as $key => $value) {
            yield $key => $predicate($value);
        }
    };
}
```

But this should throw an error:

```php
/**
 * @template T
 * @template U
 * @param callable(T): U $predicate
 * @return callable(iterable<T>): iterable<U>
 */
function map(callable $predicate): callable {
    $a = function($iter) use ($predicate): iterable {
        foreach ($iter as $key => $value) {
            yield $key => $predicate($value);
        }
    };
    return $a;
}
```

### PR DESCRIPTION
**Pull request by ragboyjr**
- Added detection for when we can infer
  closure types from parent fn return types
- Implemented functionality for infering types of
  returned closures
- Added ability to infer type of return from typed
  closures
- Added a new getFunctionLikeStorage method in
  Codebase to support easily getting a function
  despite being a method, closure, or function
- Added some utilities to the MethodIdentifier
  to facilitate creating MethodIdentifier's from
  string method references

Closes #2896

Signed-off-by: RJ Garcia <rj@bighead.net>

### CODE REVIEW

File: tests/ReturnTypeTest.php [hunk 1]
```diff
@@ -699,6 +699,147 @@ function test() {
...
+                        };
+                    }
+
+                    $res = map(function(int $i): string { return (string) $i; })([1,2,3]);
+                ',
+                'assertions' => [
+                    '$res' => 'iterable<mixed, string>',
+                ],
+            ],
+//            'infersNestedCallableReturnTypes' => [
```
Comment (muglug) [inline tests/ReturnTypeTest.php]: You can use `SKIPPED-` instead of commenting this out

Comment (ragboyjr) [reply tests/ReturnTypeTest.php]: Ah, neat, will do.

**Comment by ragboyjr** [comment]
OK, made some progress, I got the main use cases implemented and tested.

**What's Left:**

- These changes seem to have broken two tests which need to be fixed
- I need to run psalm on my changes
- I need to see about implementing nested inference of closures.

**Comment by ragboyjr** [comment]
I think i'm pretty happy with the implementation right now, how do you want to go about documenting this feature? Is this something you even want exposed in the documentation?

Part of me feels like it kind of fits will with expectations around the inferring mechanisms that psalm already supports.

**Comment by muglug** [comment]
This is awesome, thanks!
