### PR TITLE
More attribute fixes.

### LINKED ISSUE #7751: [Bug] RuntimeException Expected attribute count to match attribute storage count
Hello everybody.

Our project has been updated up to 4.22 version and after that psalm started crashing while project analyzing with the following error:

```
Uncaught Exception: RuntimeException Expected attribute count to match attribute storage count
Emitted in /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/AttributesAnalyzer.php:117
Stack trace in the forked worker:
#0 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(406): Psalm\Internal\Analyzer\AttributesAnalyzer::analyze(Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Storage\ClassLikeStorage), Array, 1, Array)
#1 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(591): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), NULL)
#2 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(206): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Context), NULL)
#3 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php(68): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#4 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(365): Psalm\Internal\Analyzer\Statements\Block\IfElse\IfAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Internal\Scope\IfConditionalScope), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Context), Array)
#5 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(517): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#6 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(206): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#7 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php(92): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#8 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(316): Psalm\Internal\Analyzer\NamespaceAnalyzer->collectAnalyzableInformation()
#9 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(193): Psalm\Internal\Analyzer\FileAnalyzer->populateCheckers(Array)
#10 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(362): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#11 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(211): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(166, '/Users/butschst...')
#12 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(428): Psalm\Internal\Fork\Pool->__construct(Object(Psalm\Config), Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#13 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#14 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(685): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#15 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/butschst...', true)
#16 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#17 {main} in /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:402
Stack trace:
#0 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(436): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(503): Psalm\Internal\Fork\Pool->wait()
#2 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(685): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#4 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/butschst...', true)
#5 /Users/butschster/Webserver/spiral/framework/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#6 {main}
(Psalm 4.22.0@fc2c6ab4d5fa5d644d8617089f012f3bb84b8703 crashed due to an uncaught Throwable)
```

You can also view the error here https://github.com/spiral/framework/runs/5412294207?check_suite_focus=true

### LINKED ISSUE #7756: Enum cases are not validated in attribute if method return type is not void
This is a really strange issue...

https://psalm.dev/r/1acc7fd0fd

### PR DESCRIPTION
**Pull request by AndrolGenhald**
- Fix case where attributes from stubs don't match declarations in the code (fixes #7751)
 - Fix returning function not analyzing attribute construction (fixes #7756)
 - Use constants for attribute targets
 
AttributeStorage isn't really used anymore, but it's still around for plugins.

### CODE REVIEW

File: src/Psalm/Internal/Analyzer/AttributesAnalyzer.php [hunk 1]
```diff
@@ -42,6 +42,16 @@ class AttributesAnalyzer
...
+    public const TARGET_METHOD = 4;
+    public const TARGET_PROPERTY = 8;
+    public const TARGET_CLASS_CONSTANT = 16;
+    public const TARGET_PARAMETER = 32;
+    public const TARGET_ALL = 63;
+    public const IS_REPEATABLE = 64;
+
     /**
      * @param array<array-key, AttributeGroup> $attribute_groups
      * @param 1|2|4|8|16|32|40 $target
```
Comment (orklah) [inline src/Psalm/Internal/Analyzer/AttributesAnalyzer.php:57]: could it be changed to an int mask now that we have constants?

Comment (AndrolGenhald) [reply src/Psalm/Internal/Analyzer/AttributesAnalyzer.php:57]: Nope, it doesn't allow arbitrary combinations. It can be `key-of<self::TARGET_DESCRIPTIONS>` though.

**Comment by orklah** [comment]
It has been broken for a few days. Symfony added a polyfill for PhpToken I believe and the Phar build doesn't like that. I haven't looked how to fix that for now

**Comment by AndrolGenhald** [comment]
Oh, yeah, I see it, I didn't rebase on master before pushing so this PR is actually "older" than the other recent PRs, that explains it.
