### PR TITLE
Fix type of property-get with coalesce

### LINKED ISSUE #11151: `@property-read` dynamic property type not working sometimes
https://psalm.dev/r/f818e2d9d9

Type of `$_c` should be `string` instead of `''|mixed`.

### PR DESCRIPTION
**Pull request by MoonE**
Fixes #11151

If the property was not already known inside the IssetAnalyzer::analyze function, it was added as mixed to the context.

This adds a check for dynamic properties.

### CODE REVIEW

File: src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php [hunk 1]
```diff
@@ -30,7 +31,16 @@ public static function analyze(
...
+                    if (isset($context->vars_in_scope['$this'])) {
+                        InstancePropertyFetchAnalyzer::analyze(
+                            $statements_analyzer,
+                            $isset_var,
+                            $context,
+                        );
+                    }
+                    if (!isset($context->vars_in_scope[$var_id])) {
+                        $context->vars_in_scope[$var_id] = Type::getMixed();
+                    }
```
Comment (MoonE) [inline src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php:43]: The return value of InstancePropertyFetchAnalyzer::analyze is discarded, not sure if/how it needs to be handled.

File: src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php [hunk 2]
```diff
@@ -30,7 +31,16 @@ public static function analyze(
                 $var_id = '$this->' . $isset_var->name->name;
 
                 if (!isset($context->vars_in_scope[$var_id])) {
-                    $context->vars_in_scope[$var_id] = Type::getMixed();
+                    if (isset($context->vars_in_scope['$this'])) {
```
Comment (MoonE) [inline src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php:34]: This check is necessary to keep this test passing:
https://github.com/vimeo/psalm/blob/3f52ded9c37a9ab227b8052e132223efd97acc44/tests/TypeReconciliation/ScopeTest.php#L165-L174

This checks if this is inside an object context and dynamic property access is possible.

**Comment by orklah** [comment]
Thanks!
