### PR TITLE
Adds support for fixing missing throws doc block

### LINKED ISSUE #7918: Add support for auto fixing missing throws doc block errors
Related to 
`checkForThrowsDocblock` option, it would be nice to auto add throws docblock to functions. 
Use case: 
Better understanding of how the function can fail for the caller, often times it is useful then to refactor the code to not catch the exception at the higher level and re throw it to provide more context

### PR DESCRIPTION
**Pull request by aszenz**
Fixes #7918

### CODE REVIEW

**Comment by orklah** [comment]
Cool! That looks nice!

If you target 4.x, you must keep compatibility with PHP 7.1 though. Can you check this and the other CI failure?

Could you also add a test case with two different exceptions, to check the docblock rendering?

File: tests/FileManipulation/ThrowsBlockAdditionTest.php [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+                    function foo(string $s): string {
+                        if("" === $s) {
+                            throw new \Exception();
+                        }
+                        return $s;
+                    }',
+                '<?php
+                    /**
+                     * @throws InvalidArgumentException|DomainException
+                     * @throws Exception
```
Comment (aszenz) [inline tests/FileManipulation/ThrowsBlockAdditionTest.php:77]: i preserve the existing throws annotation and add a new one based on inference

File: src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php [hunk 2]
```diff
@@ -719,6 +725,8 @@ public function analyze(
             }
 
             if (!$is_expected) {
+                assert(class_exists($possibly_thrown_exception));
```
Comment (aszenz) [inline src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php:728]: should i keep this assert or remove it, it makes sense for throws keyword to only contain classes which exist

File: tests/FileManipulation/ThrowsBlockAdditionTest.php [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+                        if("" === $s) {
+                            throw new \Exception();
+                        }
+                        return $s;
+                    }',
+                '7.4',
+                ['MissingThrowsDocblock'],
+                true,
+            ],
+            'doesNotAddDuplicateThrows' => [
```
Comment (aszenz) [inline tests/FileManipulation/ThrowsBlockAdditionTest.php:89]: This validates that the fix only adds exceptions which are not listed in the current throws doc block

File: tests/FileManipulation/ThrowsBlockAdditionTest.php (hunk 1 above)
Comment (aszenz) [reply tests/FileManipulation/ThrowsBlockAdditionTest.php:77]: So the fix will always add a new throws annotation which can have `Exception1|Exception2` syntax, but not modify existing one

File: src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php (hunk 2 above)
Comment (aszenz) [reply src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php:728]: ideally this check would not be needed, but that means modifying the return type for the function `getUncaughtThrows` which would be a bigger change

Comment (orklah) [reply src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php:728]: Please drop it. It's risky because classes could be stubbed or inserted through a Plugin so you can't guarantee they'll exists for Psalm to autoload

**Comment by orklah** [comment]
Seems fine to me, if you mark this as ready, I'm up to merge it :)

**Comment by aszenz** [comment]
@orklah Can this be merged or is it something to do still

**Comment by orklah** [comment]
Sorry :( I didn't get a notification on the status change! Thanks!
