### PR TITLE
Fix object constant inference

### LINKED ISSUE #7541: `use const Foo\foo;` infer const type as mixed
It seems Psalm already support const with new expression: https://psalm.dev/r/a273debeb2

But if I import const from other file Psalm infers it as mixed.

file1.php:
```php
<?php

namespace Foo;

final class Foo {}
const foo = new Foo();
```

file2.php:
```php
<?php

namespace Bar;

use const Foo\foo;

$_foo = foo;
/** @psalm-trace $_foo */ //$_foo is mixed
```

### PR DESCRIPTION
**Pull request by klimick**
Fix #7541

### CODE REVIEW

File: src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php [hunk 1]
```diff
@@ -55,7 +55,8 @@ public static function infer(
         Aliases $aliases,
         FileSource $file_source = null,
         ?array $existing_class_constants = null,
-        ?string $fq_classlike_name = null
+        ?string $fq_classlike_name = null,
+        bool $const_inference = false
```
Comment (orklah) [inline src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php:59]: why did you need to add a flag here?

**Comment by orklah** [comment]
Test failure is unrelated, but it looks like you're on an outdated revision

File: src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php (hunk 1 above)
Comment (klimick) [reply src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php]: I mistakenly thought that adding `New_` would break the existing inference.

**Comment by klimick** [comment]
> Test failure is unrelated, but it looks like you're on an outdated revision

I've rebase main branch. Tests is ok now.

**Comment by orklah** [comment]
Thanks!
